#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Devel-CallChecker
Version  : 0.008
Release  : 18
URL      : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Devel-CallChecker-0.008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Devel-CallChecker-0.008.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libd/libdevel-callchecker-perl/libdevel-callchecker-perl_0.007-2.debian.tar.xz
Summary  : 'custom op checking attached to subroutines'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-3.0
Requires: perl-Devel-CallChecker-license = %{version}-%{release}
Requires: perl-Devel-CallChecker-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(DynaLoader::Functions)

%description
NAME
Devel::CallChecker - custom op checking attached to subroutines
DESCRIPTION

%package dev
Summary: dev components for the perl-Devel-CallChecker package.
Group: Development
Provides: perl-Devel-CallChecker-devel = %{version}-%{release}
Requires: perl-Devel-CallChecker = %{version}-%{release}

%description dev
dev components for the perl-Devel-CallChecker package.


%package license
Summary: license components for the perl-Devel-CallChecker package.
Group: Default

%description license
license components for the perl-Devel-CallChecker package.


%package perl
Summary: perl components for the perl-Devel-CallChecker package.
Group: Default
Requires: perl-Devel-CallChecker = %{version}-%{release}

%description perl
perl components for the perl-Devel-CallChecker package.


%prep
%setup -q -n Devel-CallChecker-0.008
cd %{_builddir}
tar xf %{_sourcedir}/libdevel-callchecker-perl_0.007-2.debian.tar.xz
cd %{_builddir}/Devel-CallChecker-0.008
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Devel-CallChecker-0.008/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Devel-CallChecker
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Devel-CallChecker/d8c40dffb4b8722abb4a5e8b7c3c1d22b1eaf674
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Devel::CallChecker.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Devel-CallChecker/d8c40dffb4b8722abb4a5e8b7c3c1d22b1eaf674

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Devel/CallChecker.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Devel/CallChecker/CallChecker.so
