#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Devel-CallChecker
Version  : 0.008
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Devel-CallChecker-0.008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Devel-CallChecker-0.008.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libd/libdevel-callchecker-perl/libdevel-callchecker-perl_0.007-2.debian.tar.xz
Summary  : 'custom op checking attached to subroutines'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-3.0
Requires: perl-Devel-CallChecker-lib = %{version}-%{release}
Requires: perl-Devel-CallChecker-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(DynaLoader::Functions)

%description
NAME
Devel::CallChecker - custom op checking attached to subroutines
DESCRIPTION

%package dev
Summary: dev components for the perl-Devel-CallChecker package.
Group: Development
Requires: perl-Devel-CallChecker-lib = %{version}-%{release}
Provides: perl-Devel-CallChecker-devel = %{version}-%{release}

%description dev
dev components for the perl-Devel-CallChecker package.


%package lib
Summary: lib components for the perl-Devel-CallChecker package.
Group: Libraries
Requires: perl-Devel-CallChecker-license = %{version}-%{release}

%description lib
lib components for the perl-Devel-CallChecker package.


%package license
Summary: license components for the perl-Devel-CallChecker package.
Group: Default

%description license
license components for the perl-Devel-CallChecker package.


%prep
%setup -q -n Devel-CallChecker-0.008
cd ..
%setup -q -T -D -n Devel-CallChecker-0.008 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Devel-CallChecker-0.008/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Devel-CallChecker
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-Devel-CallChecker/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.0/x86_64-linux-thread-multi/Devel/CallChecker.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Devel::CallChecker.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.0/x86_64-linux-thread-multi/auto/Devel/CallChecker/CallChecker.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Devel-CallChecker/deblicense_copyright
